import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from 'next/script';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
	{/*<!-- Meta --> */}
	<meta charSet="utf-8"/>
	<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<meta name="description" content=""/>
	<meta name="keywords" content=""/>
	<meta name="author" content="Awaiken"/>
	{/*<!-- Page Title --> */}
	<title>MediPro - Hospital HTML Template</title>
	{/*<!-- Favicon Icon --> */}
	<link rel="shortcut icon" type="image/x-icon" href="https://medinsight.vercel.app/images/favicon.png"/>
    {/*<!-- Google Fonts css-->*/}
    <link rel="preconnect" href="https://fonts.googleapis.com/" crossOrigin="anonymous" />
      <link rel="preconnect" href="https://fonts.gstatic.com/" crossOrigin="anonymous" />
      <link
        href="https://fonts.googleapis.com/css2?family=Figtree:ital,wght@0,300..900;1,300..900&display=swap"
        rel="stylesheet"
      />
	{/*<!-- Bootstrap Css --> */}
	<link href="https://medinsight.vercel.app/css/bootstrap.min.css" rel="stylesheet" media="screen"/>
	{/*<!-- SlickNav Css --> */}
	<link href="https://medinsight.vercel.app/css/slicknav.min.css" rel="stylesheet"/>
	{/*<!-- Swiper Css --> */}
	<link rel="stylesheet" href="https://medinsight.vercel.app/css/swiper-bundle.min.css"/>
  <link href="https://medinsight.vercel.app/css/all.css" rel="stylesheet" media="screen"/>

	{/*<!-- Animated Css --> */}
	<link href="https://medinsight.vercel.app/css/animate.min.css" rel="stylesheet"/>
	{/*<!-- Magnific Popup core CSS file --> */}
	<link rel="stylesheet" href="https://medinsight.vercel.app/css/magnific-popup.css"/>
	{/*<!-- Main custom Css --> */}
	<link href="https://medinsight.vercel.app/css/custom.css" rel="stylesheet" media="screen"/>
</head>

      <body className={inter.className}>{children}
        
    {/*<!-- Jquery Library File -->  */}
    <Script src="https://medinsight.vercel.app/js/jquery-3.7.1.min.js"></Script>
    {/*<!-- Bootstrap js file -->  */}
    <Script src="https://medinsight.vercel.app/js/bootstrap.min.js"></Script>
    {/*<!-- Validator js file --> */}
    <Script src="https://medinsight.vercel.app/js/validator.min.js"></Script>
    {/*<!-- SlickNav js file -->  */}
    <Script src="https://medinsight.vercel.app/js/jquery.slicknav.js"></Script>
    {/*<!-- Swiper js file -->  */}
    <Script src="https://medinsight.vercel.app/js/swiper-bundle.min.js"></Script>
    {/*<!-- Counter js file -->  */}
    <Script src="https://medinsight.vercel.app/js/jquery.waypoints.min.js"></Script>
    <Script src="https://medinsight.vercel.app/js/jquery.counterup.min.js"></Script>
    {/*<!-- Magnific js file -->  */}
    <Script src="https://medinsight.vercel.app/js/jquery.magnific-popup.min.js"></Script>
    {/*<!-- SmoothScroll -->  */}
    <Script src="https://medinsight.vercel.app/js/SmoothScroll.js"></Script>
    {/*<!-- Parallax js -->  */}
    <Script src="https://medinsight.vercel.app/js/parallaxie.js"></Script>
    {/*<!-- MagicCursor js file -->  */}
    <Script src="https://medinsight.vercel.app/js/gsap.min.js"></Script>
    <Script src="https://medinsight.vercel.app/js/magiccursor.js"></Script>
    {/*<!-- Text Effect js file -->  */}
    <Script src="https://medinsight.vercel.app/js/SplitText.js"></Script>
    <Script src="https://medinsight.vercel.app/js/ScrollTrigger.min.js"></Script>
    {/*<!-- Wow js file -->  */}
    <Script src="https://medinsight.vercel.app/js/wow.js"></Script>
    {/*<!-- Main Custom js file -->  */}
    <Script src="https://medinsight.vercel.app/js/function.js"></Script>
      </body>
    </html>
  );
}
